### ISSUE TITLE
Scroll hidden 

### ISSUE THREAD

**Issue by devFortes** [e1016/naranja#2]
Hi, I saw that the scrollbar appears, here's the css to fix the problem! It worked for me.

.naranja-notification-box {
    z-index: 999;
    box-sizing: content-box;
    display: flex;
    flex-direction: column-reverse;
    position: fixed;
    bottom: 0;
    right: 0;
    width: 315px;
    height: auto;
    max-height: 100vh;
    overflow: auto;
    padding: 8px;
    padding-top: 20px
}

.naranja-notification-box::-webkit-scrollbar {
    display: none;
}

**Comment by e1016** [comment]
Can you create a pr?

**Comment by devFortes** [comment]
> Can you create a pr?

Hi, I'm new to github so I don't know how to do PR!
